use std::collections::BTreeMap;
use std::fmt::Write;

use crate::mir::{
    BasicBlock, BinaryOp, Expr, ExprKind, ItemKind, Local, Place, PlaceKind, Program, Statement,
    StatementKind, TerminatorKind, Type, UnaryOp,
};

#[derive(Clone)]
struct FunctionSignature {
    symbol: String,
    params: Vec<String>,
    return_type: String,
}

#[derive(Clone)]
struct LocalSlot {
    ptr: String,
    ty: String,
}

struct LlvmValue {
    ty: String,
    repr: String,
}

#[derive(Clone)]
struct StringLiteral {
    symbol: String,
    len: usize,
    encoded: String,
}

struct FunctionEmitter<'a> {
    signatures: &'a BTreeMap<String, FunctionSignature>,
    strings: &'a BTreeMap<String, StringLiteral>,
    locals: BTreeMap<u32, LocalSlot>,
    temp_index: u32,
}

pub fn render_program(program: &Program) -> Result<String, Vec<String>> {
    let mut unsupported = Vec::new();
    let mut signatures = BTreeMap::new();

    for item in &program.items {
        match &item.kind {
            ItemKind::Function {
                name,
                type_params,
                type_param_bounds,
                params,
                return_type,
                ..
            } => {
                if !type_params.is_empty() || !type_param_bounds.is_empty() {
                    unsupported.push(format!(
                        "function `{name}` uses generics or trait bounds, which LLVM AOT v0 does not lower"
                    ));
                    continue;
                }

                let mut lowered_params = Vec::new();
                for param in params {
                    match llvm_type(&param.ty) {
                        Some(ty) => lowered_params.push(ty.to_string()),
                        None => unsupported.push(format!(
                            "function `{name}` parameter `{}` uses unsupported type {}",
                            param.name,
                            ax_type_name(&param.ty)
                        )),
                    }
                }

                let Some(return_type) = llvm_type(return_type) else {
                    unsupported.push(format!(
                        "function `{name}` returns unsupported type {}",
                        ax_type_name(return_type)
                    ));
                    continue;
                };

                signatures.insert(
                    name.clone(),
                    FunctionSignature {
                        symbol: llvm_symbol(name),
                        params: lowered_params,
                        return_type: return_type.to_string(),
                    },
                );
            }
            ItemKind::Const { name, .. } => unsupported.push(format!(
                "top-level const `{name}` is not part of the LLVM AOT v0 subset"
            )),
            ItemKind::Struct { name, .. } => unsupported.push(format!(
                "struct `{name}` requires a native layout contract before LLVM AOT can lower it"
            )),
            ItemKind::Enum { name, .. } => unsupported.push(format!(
                "enum `{name}` requires a native layout contract before LLVM AOT can lower it"
            )),
        }
    }

    if !unsupported.is_empty() {
        return Err(unsupported);
    }

    if !signatures.contains_key("main") {
        return Err(vec![
            "LLVM AOT v0 requires an explicit `fn main() -> i32` entrypoint".to_string(),
        ]);
    }

    let strings = collect_string_literals(program);
    let mut module = String::new();
    writeln!(module, "; generated by axc LLVM AOT v0").expect("writing to string cannot fail");
    writeln!(module, "source_filename = \"axc\"").expect("writing to string cannot fail");
    writeln!(module).expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_fmt_i32 = private unnamed_addr constant [3 x i8] c\"%d\\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_fmt_str = private unnamed_addr constant [3 x i8] c\"%s\\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_text_true = private unnamed_addr constant [5 x i8] c\"true\\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_text_false = private unnamed_addr constant [6 x i8] c\"false\\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_text_space = private unnamed_addr constant [2 x i8] c\" \\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_text_newline = private unnamed_addr constant [2 x i8] c\"\\0A\\00\""
    )
    .expect("writing to string cannot fail");
    for literal in strings.values() {
        writeln!(
            module,
            "{} = private unnamed_addr constant [{} x i8] c\"{}\"",
            literal.symbol, literal.len, literal.encoded
        )
        .expect("writing to string cannot fail");
    }
    writeln!(module, "declare i32 @printf(ptr, ...)").expect("writing to string cannot fail");
    writeln!(module).expect("writing to string cannot fail");

    for item in &program.items {
        let ItemKind::Function {
            name,
            params,
            return_type,
            locals,
            entry_block,
            blocks,
            ..
        } = &item.kind
        else {
            continue;
        };

        match render_function(
            name,
            params,
            return_type,
            locals,
            *entry_block,
            blocks,
            &signatures,
            &strings,
        ) {
            Ok(function_text) => module.push_str(&function_text),
            Err(reason) => unsupported.push(reason),
        }
    }

    if unsupported.is_empty() {
        Ok(module)
    } else {
        Err(unsupported)
    }
}

fn render_function(
    name: &str,
    params: &[crate::mir::Param],
    return_type: &Type,
    locals: &[Local],
    entry_block: u32,
    blocks: &[BasicBlock],
    signatures: &BTreeMap<String, FunctionSignature>,
    strings: &BTreeMap<String, StringLiteral>,
) -> Result<String, String> {
    let signature = signatures
        .get(name)
        .ok_or_else(|| format!("internal LLVM AOT error: missing signature for `{name}`"))?;
    let declared_return_type = llvm_type(return_type)
        .ok_or_else(|| format!("function `{name}` returns an unsupported type"))?;
    if signature.return_type != declared_return_type {
        return Err(format!(
            "internal LLVM AOT error: function `{name}` signature return type drifted"
        ));
    }

    let mut emitter = FunctionEmitter {
        signatures,
        strings,
        locals: BTreeMap::new(),
        temp_index: 0,
    };

    for local in locals {
        let Some(ty) = llvm_type(&local.ty) else {
            return Err(format!(
                "function `{name}` local `{}` uses unsupported type {}",
                local.name,
                ax_type_name(&local.ty)
            ));
        };
        emitter.locals.insert(
            local.id,
            LocalSlot {
                ptr: format!("%local{}", local.id),
                ty: ty.to_string(),
            },
        );
    }

    let mut function = String::new();
    write!(
        function,
        "define {} @{}(",
        signature.return_type, signature.symbol
    )
    .expect("writing to string cannot fail");
    for (index, param) in params.iter().enumerate() {
        if index > 0 {
            write!(function, ", ").expect("writing to string cannot fail");
        }
        let Some(param_ty) = llvm_type(&param.ty) else {
            return Err(format!(
                "function `{name}` parameter `{}` uses unsupported type {}",
                param.name,
                ax_type_name(&param.ty)
            ));
        };
        write!(function, "{param_ty} %arg{}", param.local).expect("writing to string cannot fail");
    }
    writeln!(function, ") {{").expect("writing to string cannot fail");
    writeln!(function, "entry:").expect("writing to string cannot fail");

    for local in locals {
        let slot = emitter.local_slot(local.id)?;
        writeln!(function, "  {} = alloca {}", slot.ptr, slot.ty)
            .expect("writing to string cannot fail");
    }
    for param in params {
        let slot = emitter.local_slot(param.local)?;
        writeln!(
            function,
            "  store {} %arg{}, ptr {}",
            slot.ty, param.local, slot.ptr
        )
        .expect("writing to string cannot fail");
    }
    writeln!(function, "  br label %bb{entry_block}").expect("writing to string cannot fail");

    for block in blocks {
        writeln!(function, "bb{}:", block.id).expect("writing to string cannot fail");
        for statement in &block.statements {
            emitter.emit_statement(statement, &mut function)?;
        }
        emitter.emit_terminator(block, &mut function)?;
    }

    writeln!(function, "}}\n").expect("writing to string cannot fail");
    Ok(function)
}

impl<'a> FunctionEmitter<'a> {
    fn emit_statement(&mut self, statement: &Statement, out: &mut String) -> Result<(), String> {
        match &statement.kind {
            StatementKind::Let {
                local, initializer, ..
            } => {
                let slot = self.local_slot(*local)?.clone();
                let value = self.emit_expr(initializer, out)?;
                ensure_same_type(&slot.ty, &value.ty)?;
                writeln!(out, "  store {} {}, ptr {}", value.ty, value.repr, slot.ptr)
                    .expect("writing to string cannot fail");
                Ok(())
            }
            StatementKind::Assign { target, value } => {
                let slot = self.local_slot_for_place(target)?.clone();
                let value = self.emit_expr(value, out)?;
                ensure_same_type(&slot.ty, &value.ty)?;
                writeln!(out, "  store {} {}, ptr {}", value.ty, value.repr, slot.ptr)
                    .expect("writing to string cannot fail");
                Ok(())
            }
            StatementKind::Eval { expr } => {
                self.emit_expr(expr, out)?;
                Ok(())
            }
        }
    }

    fn emit_terminator(&mut self, block: &BasicBlock, out: &mut String) -> Result<(), String> {
        match &block.terminator.kind {
            TerminatorKind::Goto { target } => {
                writeln!(out, "  br label %bb{target}").expect("writing to string cannot fail");
                Ok(())
            }
            TerminatorKind::Branch {
                condition,
                then_block,
                else_block,
            } => {
                let condition = self.emit_expr(condition, out)?;
                ensure_same_type("i1", &condition.ty)?;
                writeln!(
                    out,
                    "  br i1 {}, label %bb{}, label %bb{}",
                    condition.repr, then_block, else_block
                )
                .expect("writing to string cannot fail");
                Ok(())
            }
            TerminatorKind::Return { value } => {
                let value = self.emit_expr(value, out)?;
                writeln!(out, "  ret {} {}", value.ty, value.repr)
                    .expect("writing to string cannot fail");
                Ok(())
            }
            TerminatorKind::Unreachable => {
                writeln!(out, "  unreachable").expect("writing to string cannot fail");
                Ok(())
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr, out: &mut String) -> Result<LlvmValue, String> {
        match &expr.kind {
            ExprKind::Int { value } => Ok(LlvmValue {
                ty: "i32".to_string(),
                repr: value.to_string(),
            }),
            ExprKind::Bool { value } => Ok(LlvmValue {
                ty: "i1".to_string(),
                repr: if *value { "1" } else { "0" }.to_string(),
            }),
            ExprKind::Local { local, .. } => {
                let slot = self.local_slot(*local)?.clone();
                let temp = self.next_temp();
                writeln!(out, "  {temp} = load {}, ptr {}", slot.ty, slot.ptr)
                    .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: slot.ty,
                    repr: temp,
                })
            }
            ExprKind::Unary { op, expr } => {
                let value = self.emit_expr(expr, out)?;
                match op {
                    UnaryOp::Negate => {
                        ensure_same_type("i32", &value.ty)?;
                        let temp = self.next_temp();
                        writeln!(out, "  {temp} = sub i32 0, {}", value.repr)
                            .expect("writing to string cannot fail");
                        Ok(LlvmValue {
                            ty: "i32".to_string(),
                            repr: temp,
                        })
                    }
                    UnaryOp::Not => {
                        ensure_same_type("i1", &value.ty)?;
                        let temp = self.next_temp();
                        writeln!(out, "  {temp} = xor i1 {}, 1", value.repr)
                            .expect("writing to string cannot fail");
                        Ok(LlvmValue {
                            ty: "i1".to_string(),
                            repr: temp,
                        })
                    }
                }
            }
            ExprKind::Binary { op, left, right } => {
                let left = self.emit_expr(left, out)?;
                let right = self.emit_expr(right, out)?;
                self.emit_binary(*op, left, right, out)
            }
            ExprKind::Call {
                function,
                arguments,
            } => self.emit_call(function, arguments, out),
            ExprKind::Float { .. } => Err("f32 values are not in the LLVM AOT v0 subset".into()),
            ExprKind::String { value } => {
                let literal = self
                    .strings
                    .get(value)
                    .ok_or_else(|| "internal LLVM AOT error: missing string literal".to_string())?;
                Ok(LlvmValue {
                    ty: "ptr".to_string(),
                    repr: literal.symbol.clone(),
                })
            }
            ExprKind::Const { name } => Err(format!(
                "const `{name}` is not in the LLVM AOT v0 expression subset"
            )),
            ExprKind::Try { .. } => Err(
                "`?` result propagation needs native early-return lowering before LLVM AOT can lower it"
                    .into(),
            ),
            ExprKind::StructLiteral { .. }
            | ExprKind::ArrayLiteral { .. }
            | ExprKind::Block { .. }
            | ExprKind::Match { .. }
            | ExprKind::EnumVariant { .. }
            | ExprKind::MatchTest { .. }
            | ExprKind::EnumPayload { .. }
            | ExprKind::Field { .. }
            | ExprKind::Index { .. }
            | ExprKind::Slice { .. } => {
                Err("expression requires a native layout or lowering contract outside LLVM AOT v0".into())
            }
        }
    }

    fn emit_binary(
        &mut self,
        op: BinaryOp,
        left: LlvmValue,
        right: LlvmValue,
        out: &mut String,
    ) -> Result<LlvmValue, String> {
        ensure_same_type(&left.ty, &right.ty)?;
        let temp = self.next_temp();
        match op {
            BinaryOp::Add
            | BinaryOp::Subtract
            | BinaryOp::Multiply
            | BinaryOp::Divide
            | BinaryOp::Remainder => {
                ensure_same_type("i32", &left.ty)?;
                let instruction = match op {
                    BinaryOp::Add => "add",
                    BinaryOp::Subtract => "sub",
                    BinaryOp::Multiply => "mul",
                    BinaryOp::Divide => "sdiv",
                    BinaryOp::Remainder => "srem",
                    _ => unreachable!(),
                };
                writeln!(
                    out,
                    "  {temp} = {instruction} i32 {}, {}",
                    left.repr, right.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "i32".to_string(),
                    repr: temp,
                })
            }
            BinaryOp::LogicalAnd | BinaryOp::LogicalOr => {
                ensure_same_type("i1", &left.ty)?;
                let instruction = if matches!(op, BinaryOp::LogicalAnd) {
                    "and"
                } else {
                    "or"
                };
                writeln!(
                    out,
                    "  {temp} = {instruction} i1 {}, {}",
                    left.repr, right.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "i1".to_string(),
                    repr: temp,
                })
            }
            BinaryOp::Equal | BinaryOp::NotEqual => {
                let predicate = if matches!(op, BinaryOp::Equal) {
                    "eq"
                } else {
                    "ne"
                };
                writeln!(
                    out,
                    "  {temp} = icmp {predicate} {} {}, {}",
                    left.ty, left.repr, right.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "i1".to_string(),
                    repr: temp,
                })
            }
            BinaryOp::Less | BinaryOp::LessEqual | BinaryOp::Greater | BinaryOp::GreaterEqual => {
                ensure_same_type("i32", &left.ty)?;
                let predicate = match op {
                    BinaryOp::Less => "slt",
                    BinaryOp::LessEqual => "sle",
                    BinaryOp::Greater => "sgt",
                    BinaryOp::GreaterEqual => "sge",
                    _ => unreachable!(),
                };
                writeln!(
                    out,
                    "  {temp} = icmp {predicate} i32 {}, {}",
                    left.repr, right.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "i1".to_string(),
                    repr: temp,
                })
            }
        }
    }

    fn emit_call(
        &mut self,
        function: &str,
        arguments: &[Expr],
        out: &mut String,
    ) -> Result<LlvmValue, String> {
        if function == "println" {
            return self.emit_println(arguments, out);
        }

        let signature = self.signatures.get(function).ok_or_else(|| {
            format!(
                "call to `{function}` is outside LLVM AOT v0; only direct calls to AX functions in the same file are currently lowered"
            )
        })?;
        if signature.params.len() != arguments.len() {
            return Err(format!(
                "call to `{function}` has {} argument(s), but LLVM AOT expected {}",
                arguments.len(),
                signature.params.len()
            ));
        }

        let mut rendered_args = Vec::new();
        for (argument, expected_ty) in arguments.iter().zip(&signature.params) {
            let value = self.emit_expr(argument, out)?;
            ensure_same_type(expected_ty, &value.ty)?;
            rendered_args.push(format!("{} {}", value.ty, value.repr));
        }

        let temp = self.next_temp();
        writeln!(
            out,
            "  {temp} = call {} @{}({})",
            signature.return_type,
            signature.symbol,
            rendered_args.join(", ")
        )
        .expect("writing to string cannot fail");
        Ok(LlvmValue {
            ty: signature.return_type.clone(),
            repr: temp,
        })
    }

    fn emit_println(&mut self, arguments: &[Expr], out: &mut String) -> Result<LlvmValue, String> {
        for (index, argument) in arguments.iter().enumerate() {
            if index > 0 {
                self.emit_printf_text("@.ax_text_space", out);
            }
            let value = self.emit_expr(argument, out)?;
            self.emit_print_value(value, out)?;
        }
        self.emit_printf_text("@.ax_text_newline", out);
        Ok(LlvmValue {
            ty: "void".to_string(),
            repr: String::new(),
        })
    }

    fn emit_print_value(&mut self, value: LlvmValue, out: &mut String) -> Result<(), String> {
        match value.ty.as_str() {
            "i32" => {
                writeln!(
                    out,
                    "  call i32 (ptr, ...) @printf(ptr @.ax_fmt_i32, i32 {})",
                    value.repr
                )
                .expect("writing to string cannot fail");
                Ok(())
            }
            "i1" => {
                let text = self.next_temp();
                writeln!(
                    out,
                    "  {text} = select i1 {}, ptr @.ax_text_true, ptr @.ax_text_false",
                    value.repr
                )
                .expect("writing to string cannot fail");
                writeln!(
                    out,
                    "  call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr {text})"
                )
                .expect("writing to string cannot fail");
                Ok(())
            }
            "ptr" => {
                writeln!(
                    out,
                    "  call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr {})",
                    value.repr
                )
                .expect("writing to string cannot fail");
                Ok(())
            }
            "void" => Err("println cannot print a `<void>` value in LLVM AOT v0".to_string()),
            other => Err(format!(
                "println({other}) needs a native runtime ABI before LLVM AOT can lower it"
            )),
        }
    }

    fn emit_printf_text(&mut self, global: &str, out: &mut String) {
        writeln!(
            out,
            "  call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr {global})"
        )
        .expect("writing to string cannot fail");
    }

    fn local_slot(&self, local: u32) -> Result<&LocalSlot, String> {
        self.locals
            .get(&local)
            .ok_or_else(|| format!("internal LLVM AOT error: missing local slot {local}"))
    }

    fn local_slot_for_place(&self, place: &Place) -> Result<&LocalSlot, String> {
        match &place.kind {
            PlaceKind::Local { local, .. } => self.local_slot(*local),
            PlaceKind::Field { .. } | PlaceKind::Index { .. } => Err(
                "field and index assignment require native layout support outside LLVM AOT v0"
                    .into(),
            ),
        }
    }

    fn next_temp(&mut self) -> String {
        let temp = format!("%t{}", self.temp_index);
        self.temp_index += 1;
        temp
    }
}

fn collect_string_literals(program: &Program) -> BTreeMap<String, StringLiteral> {
    let mut strings = BTreeMap::new();
    let mut next_id = 0;
    for item in &program.items {
        let ItemKind::Function { blocks, .. } = &item.kind else {
            continue;
        };
        for block in blocks {
            for statement in &block.statements {
                collect_statement_string_literals(statement, &mut strings, &mut next_id);
            }
            collect_terminator_string_literals(&block.terminator.kind, &mut strings, &mut next_id);
        }
    }
    strings
}

fn collect_statement_string_literals(
    statement: &Statement,
    strings: &mut BTreeMap<String, StringLiteral>,
    next_id: &mut usize,
) {
    match &statement.kind {
        StatementKind::Let { initializer, .. } | StatementKind::Eval { expr: initializer } => {
            collect_expr_string_literals(initializer, strings, next_id);
        }
        StatementKind::Assign { target, value } => {
            collect_place_string_literals(target, strings, next_id);
            collect_expr_string_literals(value, strings, next_id);
        }
    }
}

fn collect_terminator_string_literals(
    terminator: &TerminatorKind,
    strings: &mut BTreeMap<String, StringLiteral>,
    next_id: &mut usize,
) {
    match terminator {
        TerminatorKind::Branch { condition, .. } | TerminatorKind::Return { value: condition } => {
            collect_expr_string_literals(condition, strings, next_id);
        }
        TerminatorKind::Goto { .. } | TerminatorKind::Unreachable => {}
    }
}

fn collect_place_string_literals(
    place: &Place,
    strings: &mut BTreeMap<String, StringLiteral>,
    next_id: &mut usize,
) {
    match &place.kind {
        PlaceKind::Local { .. } => {}
        PlaceKind::Field { base, .. } => collect_place_string_literals(base, strings, next_id),
        PlaceKind::Index { base, index } => {
            collect_place_string_literals(base, strings, next_id);
            collect_expr_string_literals(index, strings, next_id);
        }
    }
}

fn collect_expr_string_literals(
    expr: &Expr,
    strings: &mut BTreeMap<String, StringLiteral>,
    next_id: &mut usize,
) {
    match &expr.kind {
        ExprKind::String { value } => {
            if !strings.contains_key(value) {
                let symbol = format!("@.ax_str_{}", *next_id);
                *next_id += 1;
                strings.insert(
                    value.clone(),
                    StringLiteral {
                        symbol,
                        len: value.len() + 1,
                        encoded: encode_llvm_c_string(value),
                    },
                );
            }
        }
        ExprKind::Unary { expr, .. }
        | ExprKind::Try { expr }
        | ExprKind::EnumPayload { value: expr }
        | ExprKind::Field { base: expr, .. } => {
            collect_expr_string_literals(expr, strings, next_id);
        }
        ExprKind::Binary { left, right, .. } => {
            collect_expr_string_literals(left, strings, next_id);
            collect_expr_string_literals(right, strings, next_id);
        }
        ExprKind::Call { arguments, .. }
        | ExprKind::ArrayLiteral {
            elements: arguments,
        } => {
            for argument in arguments {
                collect_expr_string_literals(argument, strings, next_id);
            }
        }
        ExprKind::StructLiteral { fields, .. } => {
            for field in fields {
                collect_expr_string_literals(&field.value, strings, next_id);
            }
        }
        ExprKind::Block { statements, value } => {
            for statement in statements {
                collect_statement_string_literals(statement, strings, next_id);
            }
            collect_expr_string_literals(value, strings, next_id);
        }
        ExprKind::Match { scrutinee, arms } => {
            collect_expr_string_literals(scrutinee, strings, next_id);
            for arm in arms {
                if let Some(guard) = &arm.guard {
                    collect_expr_string_literals(guard, strings, next_id);
                }
                collect_expr_string_literals(&arm.value, strings, next_id);
            }
        }
        ExprKind::EnumVariant { payload, .. } => {
            if let Some(payload) = payload {
                collect_expr_string_literals(payload, strings, next_id);
            }
        }
        ExprKind::MatchTest { scrutinee, .. } => {
            collect_expr_string_literals(scrutinee, strings, next_id);
        }
        ExprKind::Index { base, index } => {
            collect_expr_string_literals(base, strings, next_id);
            collect_expr_string_literals(index, strings, next_id);
        }
        ExprKind::Slice { base, start, end } => {
            collect_expr_string_literals(base, strings, next_id);
            collect_expr_string_literals(start, strings, next_id);
            collect_expr_string_literals(end, strings, next_id);
        }
        ExprKind::Int { .. }
        | ExprKind::Float { .. }
        | ExprKind::Bool { .. }
        | ExprKind::Local { .. }
        | ExprKind::Const { .. } => {}
    }
}

fn encode_llvm_c_string(value: &str) -> String {
    let mut encoded = String::new();
    for byte in value.as_bytes() {
        match *byte {
            b'\\' => encoded.push_str("\\5C"),
            b'"' => encoded.push_str("\\22"),
            0x20..=0x7e => encoded.push(*byte as char),
            other => write!(encoded, "\\{other:02X}").expect("writing to string cannot fail"),
        }
    }
    encoded.push_str("\\00");
    encoded
}

fn ensure_same_type(expected: &str, actual: &str) -> Result<(), String> {
    if expected == actual {
        Ok(())
    } else {
        Err(format!(
            "internal LLVM AOT type mismatch: expected {expected}, got {actual}"
        ))
    }
}

fn llvm_type(ty: &Type) -> Option<&'static str> {
    match ty {
        Type::Bool => Some("i1"),
        Type::I32 => Some("i32"),
        Type::F32
        | Type::String
        | Type::StringList
        | Type::Slice { .. }
        | Type::Array { .. }
        | Type::Struct { .. }
        | Type::StructInstance { .. }
        | Type::Enum { .. }
        | Type::EnumInstance { .. }
        | Type::TypeParam { .. } => None,
    }
}

fn llvm_symbol(name: &str) -> String {
    if name == "main" {
        return "main".to_string();
    }

    let mut symbol = String::from("ax_");
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            symbol.push(ch);
        } else {
            symbol.push('_');
        }
    }
    symbol
}

fn ax_type_name(ty: &Type) -> String {
    match ty {
        Type::Bool => "bool".to_string(),
        Type::I32 => "i32".to_string(),
        Type::F32 => "f32".to_string(),
        Type::String => "string".to_string(),
        Type::StringList => "string_list".to_string(),
        Type::Slice { element } => format!("[]{}", ax_type_name(element)),
        Type::Array { element, length } => format!("[{}; {}]", ax_type_name(element), length),
        Type::Struct { name } => name.clone(),
        Type::StructInstance { name, args } | Type::EnumInstance { name, args } => format!(
            "{}<{}>",
            name,
            args.iter().map(ax_type_name).collect::<Vec<_>>().join(", ")
        ),
        Type::Enum { name } => name.clone(),
        Type::TypeParam { name } => name.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::render_program;
    use crate::frontend::analyze;
    use crate::source::SourceFile;

    fn render(source_text: &str) -> String {
        let source = SourceFile::anonymous(source_text);
        let output = analyze(&source);
        assert!(
            output.diagnostics.is_empty(),
            "source should analyze before LLVM IR rendering: {:?}",
            output.diagnostics
        );
        render_program(output.mir.as_ref().expect("MIR should exist"))
            .expect("LLVM IR should render")
    }

    #[test]
    fn renders_minimal_main_return() {
        let rendered = render(
            "\
fn main() -> i32 {
    return 0;
}
",
        );

        assert!(rendered.contains("define i32 @main()"));
        assert!(rendered.contains("ret i32 0"));
    }

    #[test]
    fn renders_i32_function_calls_and_arithmetic() {
        let rendered = render(
            "\
fn add(left: i32, right: i32) -> i32 {
    return left + right;
}

fn main() -> i32 {
    return add(1, 2);
}
",
        );

        assert!(rendered.contains("define i32 @ax_add(i32 %arg0, i32 %arg1)"));
        assert!(rendered.contains("= add i32"));
        assert!(rendered.contains("= call i32 @ax_add(i32 1, i32 2)"));
    }

    #[test]
    fn renders_i32_and_bool_println_calls() {
        let rendered = render(
            "\
fn main() -> i32 {
    println(7);
    println(true);
    return 0;
}
",
        );

        assert!(rendered.contains("declare i32 @printf(ptr, ...)"));
        assert!(rendered.contains("call i32 (ptr, ...) @printf(ptr @.ax_fmt_i32, i32 7)"));
        assert!(rendered.contains("select i1 1, ptr @.ax_text_true, ptr @.ax_text_false"));
    }

    #[test]
    fn renders_string_literal_println_calls() {
        let rendered = render(
            "\
fn main() -> i32 {
    println(\"hello\");
    println(\"C:\\\\AX\");
    return 0;
}
",
        );

        assert!(
            rendered.contains("@.ax_str_0 = private unnamed_addr constant [6 x i8] c\"hello\\00\"")
        );
        assert!(
            rendered
                .contains("@.ax_str_1 = private unnamed_addr constant [6 x i8] c\"C:\\5CAX\\00\"")
        );
        assert!(rendered.contains("call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr @.ax_str_0)"));
    }
}
