use std::collections::BTreeMap;
use std::fmt::Write;

use crate::mir::{
    BasicBlock, BinaryOp, Expr, ExprKind, ItemKind, Local, Place, PlaceKind, Program, Statement,
    StatementKind, TerminatorKind, Type, UnaryOp,
};

#[derive(Clone)]
struct FunctionSignature {
    symbol: String,
    params: Vec<String>,
    return_type: String,
    return_ax_type: Type,
}

#[derive(Clone)]
struct LocalSlot {
    ptr: String,
    ty: String,
    ax_ty: Type,
}

struct LlvmValue {
    ty: String,
    repr: String,
    ax_ty: Option<Type>,
}

#[derive(Clone)]
struct StringLiteral {
    symbol: String,
    len: usize,
    encoded: String,
}

struct FunctionEmitter<'a> {
    signatures: &'a BTreeMap<String, FunctionSignature>,
    strings: &'a BTreeMap<String, StringLiteral>,
    locals: BTreeMap<u32, LocalSlot>,
    temp_index: u32,
}

pub fn render_program(program: &Program) -> Result<String, Vec<String>> {
    let mut unsupported = Vec::new();
    let mut signatures = BTreeMap::new();

    for item in &program.items {
        match &item.kind {
            ItemKind::Function {
                name,
                type_params,
                type_param_bounds,
                params,
                return_type,
                ..
            } => {
                if !type_params.is_empty() || !type_param_bounds.is_empty() {
                    unsupported.push(format!(
                        "function `{name}` uses generics or trait bounds, which LLVM AOT v0 does not lower"
                    ));
                    continue;
                }

                let mut lowered_params = Vec::new();
                for param in params {
                    match llvm_type(&param.ty) {
                        Some(ty) => lowered_params.push(ty),
                        None => unsupported.push(format!(
                            "function `{name}` parameter `{}` uses unsupported type {}",
                            param.name,
                            ax_type_name(&param.ty)
                        )),
                    }
                }

                let return_ax_type = return_type.clone();
                let Some(lowered_return_type) = llvm_type(return_type) else {
                    unsupported.push(format!(
                        "function `{name}` returns unsupported type {}",
                        ax_type_name(return_type)
                    ));
                    continue;
                };

                signatures.insert(
                    name.clone(),
                    FunctionSignature {
                        symbol: llvm_symbol(name),
                        params: lowered_params,
                        return_type: lowered_return_type,
                        return_ax_type,
                    },
                );
            }
            ItemKind::Const { name, .. } => unsupported.push(format!(
                "top-level const `{name}` is not part of the LLVM AOT v0 subset"
            )),
            ItemKind::Struct { name, .. } => unsupported.push(format!(
                "struct `{name}` requires a native layout contract before LLVM AOT can lower it"
            )),
            ItemKind::Enum { name, .. } => unsupported.push(format!(
                "enum `{name}` requires a native layout contract before LLVM AOT can lower it"
            )),
        }
    }

    if !unsupported.is_empty() {
        return Err(unsupported);
    }

    if !signatures.contains_key("main") {
        return Err(vec![
            "LLVM AOT v0 requires an explicit `fn main() -> i32` entrypoint".to_string(),
        ]);
    }

    let strings = collect_string_literals(program);
    let mut module = String::new();
    writeln!(module, "; generated by axc LLVM AOT v0").expect("writing to string cannot fail");
    writeln!(module, "source_filename = \"axc\"").expect("writing to string cannot fail");
    writeln!(module).expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_fmt_i32 = private unnamed_addr constant [3 x i8] c\"%d\\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_fmt_str = private unnamed_addr constant [3 x i8] c\"%s\\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_text_true = private unnamed_addr constant [5 x i8] c\"true\\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_text_false = private unnamed_addr constant [6 x i8] c\"false\\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_text_space = private unnamed_addr constant [2 x i8] c\" \\00\""
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "@.ax_text_newline = private unnamed_addr constant [2 x i8] c\"\\0A\\00\""
    )
    .expect("writing to string cannot fail");
    for literal in strings.values() {
        writeln!(
            module,
            "{} = private unnamed_addr constant [{} x i8] c\"{}\"",
            literal.symbol, literal.len, literal.encoded
        )
        .expect("writing to string cannot fail");
    }
    writeln!(module, "declare i32 @printf(ptr, ...)").expect("writing to string cannot fail");
    writeln!(module, "declare void @exit(i32)").expect("writing to string cannot fail");
    writeln!(module, "declare i32 @strcmp(ptr, ptr)").expect("writing to string cannot fail");
    writeln!(module, "declare i64 @strlen(ptr)").expect("writing to string cannot fail");
    writeln!(module, "declare ptr @malloc(i64)").expect("writing to string cannot fail");
    writeln!(module, "declare ptr @memcpy(ptr, ptr, i64)").expect("writing to string cannot fail");
    writeln!(module, "declare i32 @snprintf(ptr, i64, ptr, ...)")
        .expect("writing to string cannot fail");
    writeln!(module).expect("writing to string cannot fail");
    write_string_len_helper(&mut module);
    write_string_runtime_helpers(&mut module);

    for item in &program.items {
        let ItemKind::Function {
            name,
            params,
            return_type,
            locals,
            entry_block,
            blocks,
            ..
        } = &item.kind
        else {
            continue;
        };

        match render_function(
            name,
            params,
            return_type,
            locals,
            *entry_block,
            blocks,
            &signatures,
            &strings,
        ) {
            Ok(function_text) => module.push_str(&function_text),
            Err(reason) => unsupported.push(reason),
        }
    }

    if unsupported.is_empty() {
        Ok(module)
    } else {
        Err(unsupported)
    }
}

fn write_string_len_helper(module: &mut String) {
    writeln!(module, "define private i32 @ax_string_len(ptr %text) {{")
        .expect("writing to string cannot fail");
    writeln!(module, "entry:").expect("writing to string cannot fail");
    writeln!(module, "  br label %loop").expect("writing to string cannot fail");
    writeln!(module).expect("writing to string cannot fail");
    writeln!(module, "loop:").expect("writing to string cannot fail");
    writeln!(
        module,
        "  %index = phi i32 [0, %entry], [%next_index, %body]"
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "  %count = phi i32 [0, %entry], [%next_count, %body]"
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "  %char_ptr = getelementptr i8, ptr %text, i32 %index"
    )
    .expect("writing to string cannot fail");
    writeln!(module, "  %byte = load i8, ptr %char_ptr").expect("writing to string cannot fail");
    writeln!(module, "  %is_end = icmp eq i8 %byte, 0").expect("writing to string cannot fail");
    writeln!(module, "  br i1 %is_end, label %done, label %body")
        .expect("writing to string cannot fail");
    writeln!(module).expect("writing to string cannot fail");
    writeln!(module, "body:").expect("writing to string cannot fail");
    writeln!(module, "  %prefix = and i8 %byte, -64").expect("writing to string cannot fail");
    writeln!(module, "  %is_continuation = icmp eq i8 %prefix, -128")
        .expect("writing to string cannot fail");
    writeln!(
        module,
        "  %starts_codepoint = xor i1 %is_continuation, true"
    )
    .expect("writing to string cannot fail");
    writeln!(module, "  %delta = zext i1 %starts_codepoint to i32")
        .expect("writing to string cannot fail");
    writeln!(module, "  %next_count = add i32 %count, %delta")
        .expect("writing to string cannot fail");
    writeln!(module, "  %next_index = add i32 %index, 1").expect("writing to string cannot fail");
    writeln!(module, "  br label %loop").expect("writing to string cannot fail");
    writeln!(module).expect("writing to string cannot fail");
    writeln!(module, "done:").expect("writing to string cannot fail");
    writeln!(module, "  ret i32 %count").expect("writing to string cannot fail");
    writeln!(module, "}}\n").expect("writing to string cannot fail");
}

fn write_string_runtime_helpers(module: &mut String) {
    writeln!(
        module,
        "define private ptr @ax_string_concat(ptr %left, ptr %right) {{"
    )
    .expect("writing to string cannot fail");
    writeln!(module, "entry:").expect("writing to string cannot fail");
    writeln!(module, "  %left_len = call i64 @strlen(ptr %left)")
        .expect("writing to string cannot fail");
    writeln!(module, "  %right_len = call i64 @strlen(ptr %right)")
        .expect("writing to string cannot fail");
    writeln!(module, "  %combined_len = add i64 %left_len, %right_len")
        .expect("writing to string cannot fail");
    writeln!(module, "  %total_len = add i64 %combined_len, 1")
        .expect("writing to string cannot fail");
    writeln!(module, "  %buffer = call ptr @malloc(i64 %total_len)")
        .expect("writing to string cannot fail");
    writeln!(
        module,
        "  %copy_left = call ptr @memcpy(ptr %buffer, ptr %left, i64 %left_len)"
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "  %right_dest = getelementptr i8, ptr %buffer, i64 %left_len"
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "  %copy_right = call ptr @memcpy(ptr %right_dest, ptr %right, i64 %right_len)"
    )
    .expect("writing to string cannot fail");
    writeln!(
        module,
        "  %end = getelementptr i8, ptr %buffer, i64 %combined_len"
    )
    .expect("writing to string cannot fail");
    writeln!(module, "  store i8 0, ptr %end").expect("writing to string cannot fail");
    writeln!(module, "  ret ptr %buffer").expect("writing to string cannot fail");
    writeln!(module, "}}\n").expect("writing to string cannot fail");

    writeln!(
        module,
        "define private ptr @ax_i32_to_string(i32 %value) {{"
    )
    .expect("writing to string cannot fail");
    writeln!(module, "entry:").expect("writing to string cannot fail");
    writeln!(module, "  %buffer = call ptr @malloc(i64 12)")
        .expect("writing to string cannot fail");
    writeln!(
        module,
        "  %written = call i32 (ptr, i64, ptr, ...) @snprintf(ptr %buffer, i64 12, ptr @.ax_fmt_i32, i32 %value)"
    )
    .expect("writing to string cannot fail");
    writeln!(module, "  ret ptr %buffer").expect("writing to string cannot fail");
    writeln!(module, "}}\n").expect("writing to string cannot fail");
}

fn render_function(
    name: &str,
    params: &[crate::mir::Param],
    return_type: &Type,
    locals: &[Local],
    entry_block: u32,
    blocks: &[BasicBlock],
    signatures: &BTreeMap<String, FunctionSignature>,
    strings: &BTreeMap<String, StringLiteral>,
) -> Result<String, String> {
    let signature = signatures
        .get(name)
        .ok_or_else(|| format!("internal LLVM AOT error: missing signature for `{name}`"))?;
    let declared_return_type = llvm_type(return_type)
        .ok_or_else(|| format!("function `{name}` returns an unsupported type"))?;
    if signature.return_type != declared_return_type {
        return Err(format!(
            "internal LLVM AOT error: function `{name}` signature return type drifted"
        ));
    }

    let mut emitter = FunctionEmitter {
        signatures,
        strings,
        locals: BTreeMap::new(),
        temp_index: 0,
    };

    for local in locals {
        let Some(ty) = llvm_type(&local.ty) else {
            return Err(format!(
                "function `{name}` local `{}` uses unsupported type {}",
                local.name,
                ax_type_name(&local.ty)
            ));
        };
        emitter.locals.insert(
            local.id,
            LocalSlot {
                ptr: format!("%local{}", local.id),
                ty,
                ax_ty: local.ty.clone(),
            },
        );
    }

    let mut function = String::new();
    write!(
        function,
        "define {} @{}(",
        signature.return_type, signature.symbol
    )
    .expect("writing to string cannot fail");
    for (index, param) in params.iter().enumerate() {
        if index > 0 {
            write!(function, ", ").expect("writing to string cannot fail");
        }
        let Some(param_ty) = llvm_type(&param.ty) else {
            return Err(format!(
                "function `{name}` parameter `{}` uses unsupported type {}",
                param.name,
                ax_type_name(&param.ty)
            ));
        };
        write!(function, "{param_ty} %arg{}", param.local).expect("writing to string cannot fail");
    }
    writeln!(function, ") {{").expect("writing to string cannot fail");
    writeln!(function, "entry:").expect("writing to string cannot fail");

    for local in locals {
        let slot = emitter.local_slot(local.id)?;
        writeln!(function, "  {} = alloca {}", slot.ptr, slot.ty)
            .expect("writing to string cannot fail");
    }
    for param in params {
        let slot = emitter.local_slot(param.local)?;
        writeln!(
            function,
            "  store {} %arg{}, ptr {}",
            slot.ty, param.local, slot.ptr
        )
        .expect("writing to string cannot fail");
    }
    writeln!(function, "  br label %bb{entry_block}").expect("writing to string cannot fail");

    for block in blocks {
        writeln!(function, "bb{}:", block.id).expect("writing to string cannot fail");
        for statement in &block.statements {
            emitter.emit_statement(statement, &mut function)?;
        }
        emitter.emit_terminator(block, &mut function)?;
    }

    writeln!(function, "}}\n").expect("writing to string cannot fail");
    Ok(function)
}

impl<'a> FunctionEmitter<'a> {
    fn emit_statement(&mut self, statement: &Statement, out: &mut String) -> Result<(), String> {
        match &statement.kind {
            StatementKind::Let {
                local, initializer, ..
            } => {
                let slot = self.local_slot(*local)?.clone();
                let value = self.emit_expr(initializer, out)?;
                ensure_same_type(&slot.ty, &value.ty)?;
                writeln!(out, "  store {} {}, ptr {}", value.ty, value.repr, slot.ptr)
                    .expect("writing to string cannot fail");
                Ok(())
            }
            StatementKind::Assign { target, value } => {
                let slot = self.local_slot_for_place(target)?.clone();
                let value = self.emit_expr(value, out)?;
                ensure_same_type(&slot.ty, &value.ty)?;
                writeln!(out, "  store {} {}, ptr {}", value.ty, value.repr, slot.ptr)
                    .expect("writing to string cannot fail");
                Ok(())
            }
            StatementKind::Eval { expr } => {
                self.emit_expr(expr, out)?;
                Ok(())
            }
        }
    }

    fn emit_terminator(&mut self, block: &BasicBlock, out: &mut String) -> Result<(), String> {
        match &block.terminator.kind {
            TerminatorKind::Goto { target } => {
                writeln!(out, "  br label %bb{target}").expect("writing to string cannot fail");
                Ok(())
            }
            TerminatorKind::Branch {
                condition,
                then_block,
                else_block,
            } => {
                let condition = self.emit_expr(condition, out)?;
                ensure_same_type("i1", &condition.ty)?;
                writeln!(
                    out,
                    "  br i1 {}, label %bb{}, label %bb{}",
                    condition.repr, then_block, else_block
                )
                .expect("writing to string cannot fail");
                Ok(())
            }
            TerminatorKind::Return { value } => {
                let value = self.emit_expr(value, out)?;
                writeln!(out, "  ret {} {}", value.ty, value.repr)
                    .expect("writing to string cannot fail");
                Ok(())
            }
            TerminatorKind::Unreachable => {
                writeln!(out, "  unreachable").expect("writing to string cannot fail");
                Ok(())
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr, out: &mut String) -> Result<LlvmValue, String> {
        match &expr.kind {
            ExprKind::Int { value } => Ok(LlvmValue {
                ty: "i32".to_string(),
                repr: value.to_string(),
                ax_ty: Some(Type::I32),
            }),
            ExprKind::Bool { value } => Ok(LlvmValue {
                ty: "i1".to_string(),
                repr: if *value { "1" } else { "0" }.to_string(),
                ax_ty: Some(Type::Bool),
            }),
            ExprKind::Local { local, .. } => {
                let slot = self.local_slot(*local)?.clone();
                let temp = self.next_temp();
                writeln!(out, "  {temp} = load {}, ptr {}", slot.ty, slot.ptr)
                    .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: slot.ty,
                    repr: temp,
                    ax_ty: Some(slot.ax_ty),
                })
            }
            ExprKind::Unary { op, expr } => {
                let value = self.emit_expr(expr, out)?;
                match op {
                    UnaryOp::Negate => {
                        ensure_same_type("i32", &value.ty)?;
                        let temp = self.next_temp();
                        writeln!(out, "  {temp} = sub i32 0, {}", value.repr)
                            .expect("writing to string cannot fail");
                        Ok(LlvmValue {
                            ty: "i32".to_string(),
                            repr: temp,
                            ax_ty: Some(Type::I32),
                        })
                    }
                    UnaryOp::Not => {
                        ensure_same_type("i1", &value.ty)?;
                        let temp = self.next_temp();
                        writeln!(out, "  {temp} = xor i1 {}, 1", value.repr)
                            .expect("writing to string cannot fail");
                        Ok(LlvmValue {
                            ty: "i1".to_string(),
                            repr: temp,
                            ax_ty: Some(Type::Bool),
                        })
                    }
                }
            }
            ExprKind::Binary { op, left, right } => {
                let left = self.emit_expr(left, out)?;
                let right = self.emit_expr(right, out)?;
                self.emit_binary(*op, left, right, out)
            }
            ExprKind::Call {
                function,
                arguments,
            } => self.emit_call(function, arguments, out),
            ExprKind::Float { .. } => Err("f32 values are not in the LLVM AOT v0 subset".into()),
            ExprKind::String { value } => {
                let literal = self
                    .strings
                    .get(value)
                    .ok_or_else(|| "internal LLVM AOT error: missing string literal".to_string())?;
                Ok(LlvmValue {
                    ty: "ptr".to_string(),
                    repr: literal.symbol.clone(),
                    ax_ty: Some(Type::String),
                })
            }
            ExprKind::Const { name } => Err(format!(
                "const `{name}` is not in the LLVM AOT v0 expression subset"
            )),
            ExprKind::Try { .. } => Err(
                "`?` result propagation needs native early-return lowering before LLVM AOT can lower it"
                    .into(),
            ),
            ExprKind::ArrayLiteral { elements } => self.emit_array_literal(elements, out),
            ExprKind::Index { base, index } => self.emit_index(base, index, out),
            ExprKind::StructLiteral { .. }
            | ExprKind::Block { .. }
            | ExprKind::Match { .. }
            | ExprKind::EnumVariant { .. }
            | ExprKind::MatchTest { .. }
            | ExprKind::EnumPayload { .. }
            | ExprKind::Field { .. }
            | ExprKind::Slice { .. } => {
                Err("expression requires a native layout or lowering contract outside LLVM AOT v0".into())
            }
        }
    }

    fn emit_array_literal(
        &mut self,
        elements: &[Expr],
        out: &mut String,
    ) -> Result<LlvmValue, String> {
        if elements.is_empty() {
            return Err(
                "empty array literals need explicit native array type propagation before LLVM AOT can lower them"
                    .into(),
            );
        }

        let mut rendered_elements = Vec::new();
        let mut element_ty: Option<String> = None;
        let mut element_ax_ty: Option<Type> = None;
        for element in elements {
            let value = self.emit_expr(element, out)?;
            if let Some(expected_ty) = &element_ty {
                ensure_same_type(expected_ty, &value.ty)?;
            } else {
                element_ty = Some(value.ty.clone());
            }
            if let Some(expected_ax_ty) = &element_ax_ty {
                if value.ax_ty.as_ref() != Some(expected_ax_ty) {
                    return Err("array literal elements must have one LLVM AOT type".to_string());
                }
            } else {
                element_ax_ty = value.ax_ty.clone();
            }
            rendered_elements.push(format!("{} {}", value.ty, value.repr));
        }

        let element_ty = element_ty.expect("non-empty array should have an element type");
        let element_ax_ty = element_ax_ty.ok_or_else(|| {
            "array literal element type is not representable in LLVM AOT v0".to_string()
        })?;
        let length = elements.len();
        let array_ty = format!("[{length} x {element_ty}]");
        Ok(LlvmValue {
            ty: array_ty,
            repr: format!("[{}]", rendered_elements.join(", ")),
            ax_ty: Some(Type::Array {
                element: Box::new(element_ax_ty),
                length,
            }),
        })
    }

    fn emit_index(
        &mut self,
        base: &Expr,
        index: &Expr,
        out: &mut String,
    ) -> Result<LlvmValue, String> {
        let (array_ptr, array_ty, element_ty, length, element_ax_ty) =
            self.emit_array_base_ptr(base, out)?;
        let index = self.emit_expr(index, out)?;
        ensure_same_type("i32", &index.ty)?;
        self.emit_array_bounds_check(&index.repr, length, out);
        let element_ptr = self.next_temp();
        writeln!(
            out,
            "  {element_ptr} = getelementptr {array_ty}, ptr {array_ptr}, i32 0, i32 {}",
            index.repr
        )
        .expect("writing to string cannot fail");
        let loaded = self.next_temp();
        writeln!(out, "  {loaded} = load {element_ty}, ptr {element_ptr}")
            .expect("writing to string cannot fail");
        Ok(LlvmValue {
            ty: element_ty,
            repr: loaded,
            ax_ty: Some(element_ax_ty),
        })
    }

    fn emit_array_base_ptr(
        &mut self,
        base: &Expr,
        out: &mut String,
    ) -> Result<(String, String, String, usize, Type), String> {
        if let ExprKind::Local { local, .. } = &base.kind {
            let slot = self.local_slot(*local)?.clone();
            let (array_ty, element_ty, length, element_ax_ty) = array_type_parts(&slot.ax_ty)?;
            ensure_same_type(&array_ty, &slot.ty)?;
            return Ok((slot.ptr, array_ty, element_ty, length, element_ax_ty));
        }

        let value = self.emit_expr(base, out)?;
        let Some(ax_ty) = value.ax_ty.clone() else {
            return Err("array index base is not a fixed-size array in LLVM AOT v0".to_string());
        };
        let (array_ty, element_ty, length, element_ax_ty) = array_type_parts(&ax_ty)?;
        ensure_same_type(&array_ty, &value.ty)?;
        let temp_array = self.next_temp();
        writeln!(out, "  {temp_array} = alloca {array_ty}").expect("writing to string cannot fail");
        writeln!(out, "  store {array_ty} {}, ptr {temp_array}", value.repr)
            .expect("writing to string cannot fail");
        Ok((temp_array, array_ty, element_ty, length, element_ax_ty))
    }

    fn emit_array_bounds_check(&mut self, index: &str, length: usize, out: &mut String) {
        let negative = self.next_temp();
        let too_high = self.next_temp();
        let out_of_bounds = self.next_temp();
        let fail_label = self.next_label("array_oob");
        let ok_label = self.next_label("array_ok");
        writeln!(out, "  {negative} = icmp slt i32 {index}, 0")
            .expect("writing to string cannot fail");
        writeln!(out, "  {too_high} = icmp sge i32 {index}, {length}")
            .expect("writing to string cannot fail");
        writeln!(out, "  {out_of_bounds} = or i1 {negative}, {too_high}")
            .expect("writing to string cannot fail");
        writeln!(
            out,
            "  br i1 {out_of_bounds}, label %{fail_label}, label %{ok_label}"
        )
        .expect("writing to string cannot fail");
        writeln!(out, "{fail_label}:").expect("writing to string cannot fail");
        writeln!(out, "  call void @exit(i32 1)").expect("writing to string cannot fail");
        writeln!(out, "  unreachable").expect("writing to string cannot fail");
        writeln!(out, "{ok_label}:").expect("writing to string cannot fail");
    }

    fn emit_binary(
        &mut self,
        op: BinaryOp,
        left: LlvmValue,
        right: LlvmValue,
        out: &mut String,
    ) -> Result<LlvmValue, String> {
        ensure_same_type(&left.ty, &right.ty)?;
        let temp = self.next_temp();
        match op {
            BinaryOp::Add
            | BinaryOp::Subtract
            | BinaryOp::Multiply
            | BinaryOp::Divide
            | BinaryOp::Remainder => {
                if left.ty == "ptr" {
                    if matches!(op, BinaryOp::Add) {
                        writeln!(
                            out,
                            "  {temp} = call ptr @ax_string_concat(ptr {}, ptr {})",
                            left.repr, right.repr
                        )
                        .expect("writing to string cannot fail");
                        return Ok(LlvmValue {
                            ty: "ptr".to_string(),
                            repr: temp,
                            ax_ty: Some(Type::String),
                        });
                    }
                    return Err(format!(
                        "string values do not support `{}` in LLVM AOT v0",
                        llvm_binary_op_name(op)
                    ));
                }
                ensure_same_type("i32", &left.ty)?;
                let instruction = match op {
                    BinaryOp::Add => "add",
                    BinaryOp::Subtract => "sub",
                    BinaryOp::Multiply => "mul",
                    BinaryOp::Divide => "sdiv",
                    BinaryOp::Remainder => "srem",
                    _ => unreachable!(),
                };
                writeln!(
                    out,
                    "  {temp} = {instruction} i32 {}, {}",
                    left.repr, right.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "i32".to_string(),
                    repr: temp,
                    ax_ty: Some(Type::I32),
                })
            }
            BinaryOp::LogicalAnd | BinaryOp::LogicalOr => {
                ensure_same_type("i1", &left.ty)?;
                let instruction = if matches!(op, BinaryOp::LogicalAnd) {
                    "and"
                } else {
                    "or"
                };
                writeln!(
                    out,
                    "  {temp} = {instruction} i1 {}, {}",
                    left.repr, right.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "i1".to_string(),
                    repr: temp,
                    ax_ty: Some(Type::Bool),
                })
            }
            BinaryOp::Equal | BinaryOp::NotEqual => {
                if left.ty == "ptr" {
                    let compare = temp;
                    let result = self.next_temp();
                    writeln!(
                        out,
                        "  {compare} = call i32 @strcmp(ptr {}, ptr {})",
                        left.repr, right.repr
                    )
                    .expect("writing to string cannot fail");
                    let predicate = if matches!(op, BinaryOp::Equal) {
                        "eq"
                    } else {
                        "ne"
                    };
                    writeln!(out, "  {result} = icmp {predicate} i32 {compare}, 0")
                        .expect("writing to string cannot fail");
                    return Ok(LlvmValue {
                        ty: "i1".to_string(),
                        repr: result,
                        ax_ty: Some(Type::Bool),
                    });
                }
                let predicate = if matches!(op, BinaryOp::Equal) {
                    "eq"
                } else {
                    "ne"
                };
                writeln!(
                    out,
                    "  {temp} = icmp {predicate} {} {}, {}",
                    left.ty, left.repr, right.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "i1".to_string(),
                    repr: temp,
                    ax_ty: Some(Type::Bool),
                })
            }
            BinaryOp::Less | BinaryOp::LessEqual | BinaryOp::Greater | BinaryOp::GreaterEqual => {
                ensure_same_type("i32", &left.ty)?;
                let predicate = match op {
                    BinaryOp::Less => "slt",
                    BinaryOp::LessEqual => "sle",
                    BinaryOp::Greater => "sgt",
                    BinaryOp::GreaterEqual => "sge",
                    _ => unreachable!(),
                };
                writeln!(
                    out,
                    "  {temp} = icmp {predicate} i32 {}, {}",
                    left.repr, right.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "i1".to_string(),
                    repr: temp,
                    ax_ty: Some(Type::Bool),
                })
            }
        }
    }

    fn emit_call(
        &mut self,
        function: &str,
        arguments: &[Expr],
        out: &mut String,
    ) -> Result<LlvmValue, String> {
        if function == "println" {
            return self.emit_println(arguments, out);
        }
        if function == "string_len" || function == "len" {
            return self.emit_string_len(function, arguments, out);
        }
        if function == "to_string" {
            return self.emit_to_string(arguments, out);
        }

        let signature = self.signatures.get(function).ok_or_else(|| {
            format!(
                "call to `{function}` is outside LLVM AOT v0; only direct calls to AX functions in the same file are currently lowered"
            )
        })?;
        if signature.params.len() != arguments.len() {
            return Err(format!(
                "call to `{function}` has {} argument(s), but LLVM AOT expected {}",
                arguments.len(),
                signature.params.len()
            ));
        }

        let mut rendered_args = Vec::new();
        for (argument, expected_ty) in arguments.iter().zip(&signature.params) {
            let value = self.emit_expr(argument, out)?;
            ensure_same_type(expected_ty, &value.ty)?;
            rendered_args.push(format!("{} {}", value.ty, value.repr));
        }

        let temp = self.next_temp();
        writeln!(
            out,
            "  {temp} = call {} @{}({})",
            signature.return_type,
            signature.symbol,
            rendered_args.join(", ")
        )
        .expect("writing to string cannot fail");
        Ok(LlvmValue {
            ty: signature.return_type.clone(),
            repr: temp,
            ax_ty: Some(signature.return_ax_type.clone()),
        })
    }

    fn emit_string_len(
        &mut self,
        function: &str,
        arguments: &[Expr],
        out: &mut String,
    ) -> Result<LlvmValue, String> {
        if arguments.len() != 1 {
            return Err(format!(
                "call to `{function}` has {} argument(s), but LLVM AOT expected 1",
                arguments.len()
            ));
        }
        let value = self.emit_expr(&arguments[0], out)?;
        if function == "len" {
            if let Some(Type::Array { length, .. }) = value.ax_ty {
                return Ok(LlvmValue {
                    ty: "i32".to_string(),
                    repr: length.to_string(),
                    ax_ty: Some(Type::I32),
                });
            }
        }
        if value.ty != "ptr" {
            return Err(format!(
                "{function}({}) needs a native layout or runtime ABI before LLVM AOT can lower it",
                value.ty
            ));
        }
        let temp = self.next_temp();
        writeln!(
            out,
            "  {temp} = call i32 @ax_string_len(ptr {})",
            value.repr
        )
        .expect("writing to string cannot fail");
        Ok(LlvmValue {
            ty: "i32".to_string(),
            repr: temp,
            ax_ty: Some(Type::I32),
        })
    }

    fn emit_to_string(
        &mut self,
        arguments: &[Expr],
        out: &mut String,
    ) -> Result<LlvmValue, String> {
        if arguments.len() != 1 {
            return Err(format!(
                "call to `to_string` has {} argument(s), but LLVM AOT expected 1",
                arguments.len()
            ));
        }
        let value = self.emit_expr(&arguments[0], out)?;
        match value.ty.as_str() {
            "i32" => {
                let temp = self.next_temp();
                writeln!(
                    out,
                    "  {temp} = call ptr @ax_i32_to_string(i32 {})",
                    value.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "ptr".to_string(),
                    repr: temp,
                    ax_ty: Some(Type::String),
                })
            }
            "i1" => {
                let temp = self.next_temp();
                writeln!(
                    out,
                    "  {temp} = select i1 {}, ptr @.ax_text_true, ptr @.ax_text_false",
                    value.repr
                )
                .expect("writing to string cannot fail");
                Ok(LlvmValue {
                    ty: "ptr".to_string(),
                    repr: temp,
                    ax_ty: Some(Type::String),
                })
            }
            "ptr" => Ok(value),
            "void" => Err("to_string cannot format a `<void>` value in LLVM AOT v0".to_string()),
            other => Err(format!(
                "to_string({other}) needs a native runtime formatter before LLVM AOT can lower it"
            )),
        }
    }

    fn emit_println(&mut self, arguments: &[Expr], out: &mut String) -> Result<LlvmValue, String> {
        for (index, argument) in arguments.iter().enumerate() {
            if index > 0 {
                self.emit_printf_text("@.ax_text_space", out);
            }
            let value = self.emit_expr(argument, out)?;
            self.emit_print_value(value, out)?;
        }
        self.emit_printf_text("@.ax_text_newline", out);
        Ok(LlvmValue {
            ty: "void".to_string(),
            repr: String::new(),
            ax_ty: None,
        })
    }

    fn emit_print_value(&mut self, value: LlvmValue, out: &mut String) -> Result<(), String> {
        match value.ty.as_str() {
            "i32" => {
                writeln!(
                    out,
                    "  call i32 (ptr, ...) @printf(ptr @.ax_fmt_i32, i32 {})",
                    value.repr
                )
                .expect("writing to string cannot fail");
                Ok(())
            }
            "i1" => {
                let text = self.next_temp();
                writeln!(
                    out,
                    "  {text} = select i1 {}, ptr @.ax_text_true, ptr @.ax_text_false",
                    value.repr
                )
                .expect("writing to string cannot fail");
                writeln!(
                    out,
                    "  call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr {text})"
                )
                .expect("writing to string cannot fail");
                Ok(())
            }
            "ptr" => {
                writeln!(
                    out,
                    "  call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr {})",
                    value.repr
                )
                .expect("writing to string cannot fail");
                Ok(())
            }
            "void" => Err("println cannot print a `<void>` value in LLVM AOT v0".to_string()),
            other => Err(format!(
                "println({other}) needs a native runtime ABI before LLVM AOT can lower it"
            )),
        }
    }

    fn emit_printf_text(&mut self, global: &str, out: &mut String) {
        writeln!(
            out,
            "  call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr {global})"
        )
        .expect("writing to string cannot fail");
    }

    fn local_slot(&self, local: u32) -> Result<&LocalSlot, String> {
        self.locals
            .get(&local)
            .ok_or_else(|| format!("internal LLVM AOT error: missing local slot {local}"))
    }

    fn local_slot_for_place(&self, place: &Place) -> Result<&LocalSlot, String> {
        match &place.kind {
            PlaceKind::Local { local, .. } => self.local_slot(*local),
            PlaceKind::Field { .. } | PlaceKind::Index { .. } => Err(
                "field and index assignment require native layout support outside LLVM AOT v0"
                    .into(),
            ),
        }
    }

    fn next_temp(&mut self) -> String {
        let temp = format!("%t{}", self.temp_index);
        self.temp_index += 1;
        temp
    }

    fn next_label(&mut self, prefix: &str) -> String {
        let label = format!("{}_{}", prefix, self.temp_index);
        self.temp_index += 1;
        label
    }
}

fn collect_string_literals(program: &Program) -> BTreeMap<String, StringLiteral> {
    let mut strings = BTreeMap::new();
    let mut next_id = 0;
    for item in &program.items {
        let ItemKind::Function { blocks, .. } = &item.kind else {
            continue;
        };
        for block in blocks {
            for statement in &block.statements {
                collect_statement_string_literals(statement, &mut strings, &mut next_id);
            }
            collect_terminator_string_literals(&block.terminator.kind, &mut strings, &mut next_id);
        }
    }
    strings
}

fn collect_statement_string_literals(
    statement: &Statement,
    strings: &mut BTreeMap<String, StringLiteral>,
    next_id: &mut usize,
) {
    match &statement.kind {
        StatementKind::Let { initializer, .. } | StatementKind::Eval { expr: initializer } => {
            collect_expr_string_literals(initializer, strings, next_id);
        }
        StatementKind::Assign { target, value } => {
            collect_place_string_literals(target, strings, next_id);
            collect_expr_string_literals(value, strings, next_id);
        }
    }
}

fn collect_terminator_string_literals(
    terminator: &TerminatorKind,
    strings: &mut BTreeMap<String, StringLiteral>,
    next_id: &mut usize,
) {
    match terminator {
        TerminatorKind::Branch { condition, .. } | TerminatorKind::Return { value: condition } => {
            collect_expr_string_literals(condition, strings, next_id);
        }
        TerminatorKind::Goto { .. } | TerminatorKind::Unreachable => {}
    }
}

fn collect_place_string_literals(
    place: &Place,
    strings: &mut BTreeMap<String, StringLiteral>,
    next_id: &mut usize,
) {
    match &place.kind {
        PlaceKind::Local { .. } => {}
        PlaceKind::Field { base, .. } => collect_place_string_literals(base, strings, next_id),
        PlaceKind::Index { base, index } => {
            collect_place_string_literals(base, strings, next_id);
            collect_expr_string_literals(index, strings, next_id);
        }
    }
}

fn collect_expr_string_literals(
    expr: &Expr,
    strings: &mut BTreeMap<String, StringLiteral>,
    next_id: &mut usize,
) {
    match &expr.kind {
        ExprKind::String { value } => {
            if !strings.contains_key(value) {
                let symbol = format!("@.ax_str_{}", *next_id);
                *next_id += 1;
                strings.insert(
                    value.clone(),
                    StringLiteral {
                        symbol,
                        len: value.len() + 1,
                        encoded: encode_llvm_c_string(value),
                    },
                );
            }
        }
        ExprKind::Unary { expr, .. }
        | ExprKind::Try { expr }
        | ExprKind::EnumPayload { value: expr }
        | ExprKind::Field { base: expr, .. } => {
            collect_expr_string_literals(expr, strings, next_id);
        }
        ExprKind::Binary { left, right, .. } => {
            collect_expr_string_literals(left, strings, next_id);
            collect_expr_string_literals(right, strings, next_id);
        }
        ExprKind::Call { arguments, .. }
        | ExprKind::ArrayLiteral {
            elements: arguments,
        } => {
            for argument in arguments {
                collect_expr_string_literals(argument, strings, next_id);
            }
        }
        ExprKind::StructLiteral { fields, .. } => {
            for field in fields {
                collect_expr_string_literals(&field.value, strings, next_id);
            }
        }
        ExprKind::Block { statements, value } => {
            for statement in statements {
                collect_statement_string_literals(statement, strings, next_id);
            }
            collect_expr_string_literals(value, strings, next_id);
        }
        ExprKind::Match { scrutinee, arms } => {
            collect_expr_string_literals(scrutinee, strings, next_id);
            for arm in arms {
                if let Some(guard) = &arm.guard {
                    collect_expr_string_literals(guard, strings, next_id);
                }
                collect_expr_string_literals(&arm.value, strings, next_id);
            }
        }
        ExprKind::EnumVariant { payload, .. } => {
            if let Some(payload) = payload {
                collect_expr_string_literals(payload, strings, next_id);
            }
        }
        ExprKind::MatchTest { scrutinee, .. } => {
            collect_expr_string_literals(scrutinee, strings, next_id);
        }
        ExprKind::Index { base, index } => {
            collect_expr_string_literals(base, strings, next_id);
            collect_expr_string_literals(index, strings, next_id);
        }
        ExprKind::Slice { base, start, end } => {
            collect_expr_string_literals(base, strings, next_id);
            collect_expr_string_literals(start, strings, next_id);
            collect_expr_string_literals(end, strings, next_id);
        }
        ExprKind::Int { .. }
        | ExprKind::Float { .. }
        | ExprKind::Bool { .. }
        | ExprKind::Local { .. }
        | ExprKind::Const { .. } => {}
    }
}

fn encode_llvm_c_string(value: &str) -> String {
    let mut encoded = String::new();
    for byte in value.as_bytes() {
        match *byte {
            b'\\' => encoded.push_str("\\5C"),
            b'"' => encoded.push_str("\\22"),
            0x20..=0x7e => encoded.push(*byte as char),
            other => write!(encoded, "\\{other:02X}").expect("writing to string cannot fail"),
        }
    }
    encoded.push_str("\\00");
    encoded
}

fn ensure_same_type(expected: &str, actual: &str) -> Result<(), String> {
    if expected == actual {
        Ok(())
    } else {
        Err(format!(
            "internal LLVM AOT type mismatch: expected {expected}, got {actual}"
        ))
    }
}

fn llvm_binary_op_name(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::LogicalOr => "||",
        BinaryOp::LogicalAnd => "&&",
        BinaryOp::Add => "+",
        BinaryOp::Subtract => "-",
        BinaryOp::Multiply => "*",
        BinaryOp::Divide => "/",
        BinaryOp::Remainder => "%",
        BinaryOp::Equal => "==",
        BinaryOp::NotEqual => "!=",
        BinaryOp::Less => "<",
        BinaryOp::LessEqual => "<=",
        BinaryOp::Greater => ">",
        BinaryOp::GreaterEqual => ">=",
    }
}

fn llvm_type(ty: &Type) -> Option<String> {
    match ty {
        Type::Bool => Some("i1".to_string()),
        Type::I32 => Some("i32".to_string()),
        Type::String => Some("ptr".to_string()),
        Type::Array { element, length } => {
            let element_ty = llvm_type(element)?;
            Some(format!("[{length} x {element_ty}]"))
        }
        Type::F32
        | Type::StringList
        | Type::Slice { .. }
        | Type::Struct { .. }
        | Type::StructInstance { .. }
        | Type::Enum { .. }
        | Type::EnumInstance { .. }
        | Type::TypeParam { .. } => None,
    }
}

fn array_type_parts(ty: &Type) -> Result<(String, String, usize, Type), String> {
    let Type::Array { element, length } = ty else {
        return Err("array index base is not a fixed-size array in LLVM AOT v0".to_string());
    };
    let array_ty = llvm_type(ty)
        .ok_or_else(|| format!("array type {} is outside LLVM AOT v0", ax_type_name(ty)))?;
    let element_ty = llvm_type(element).ok_or_else(|| {
        format!(
            "array element type {} is outside LLVM AOT v0",
            ax_type_name(element)
        )
    })?;
    Ok((array_ty, element_ty, *length, element.as_ref().clone()))
}

fn llvm_symbol(name: &str) -> String {
    if name == "main" {
        return "main".to_string();
    }

    let mut symbol = String::from("ax_");
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            symbol.push(ch);
        } else {
            symbol.push('_');
        }
    }
    symbol
}

fn ax_type_name(ty: &Type) -> String {
    match ty {
        Type::Bool => "bool".to_string(),
        Type::I32 => "i32".to_string(),
        Type::F32 => "f32".to_string(),
        Type::String => "string".to_string(),
        Type::StringList => "string_list".to_string(),
        Type::Slice { element } => format!("[]{}", ax_type_name(element)),
        Type::Array { element, length } => format!("[{}; {}]", ax_type_name(element), length),
        Type::Struct { name } => name.clone(),
        Type::StructInstance { name, args } | Type::EnumInstance { name, args } => format!(
            "{}<{}>",
            name,
            args.iter().map(ax_type_name).collect::<Vec<_>>().join(", ")
        ),
        Type::Enum { name } => name.clone(),
        Type::TypeParam { name } => name.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::render_program;
    use crate::frontend::analyze;
    use crate::source::SourceFile;

    fn render(source_text: &str) -> String {
        let source = SourceFile::anonymous(source_text);
        let output = analyze(&source);
        assert!(
            output.diagnostics.is_empty(),
            "source should analyze before LLVM IR rendering: {:?}",
            output.diagnostics
        );
        render_program(output.mir.as_ref().expect("MIR should exist"))
            .expect("LLVM IR should render")
    }

    #[test]
    fn renders_minimal_main_return() {
        let rendered = render(
            "\
fn main() -> i32 {
    return 0;
}
",
        );

        assert!(rendered.contains("define i32 @main()"));
        assert!(rendered.contains("ret i32 0"));
    }

    #[test]
    fn renders_i32_function_calls_and_arithmetic() {
        let rendered = render(
            "\
fn add(left: i32, right: i32) -> i32 {
    return left + right;
}

fn main() -> i32 {
    return add(1, 2);
}
",
        );

        assert!(rendered.contains("define i32 @ax_add(i32 %arg0, i32 %arg1)"));
        assert!(rendered.contains("= add i32"));
        assert!(rendered.contains("= call i32 @ax_add(i32 1, i32 2)"));
    }

    #[test]
    fn renders_i32_and_bool_println_calls() {
        let rendered = render(
            "\
fn main() -> i32 {
    println(7);
    println(true);
    return 0;
}
",
        );

        assert!(rendered.contains("declare i32 @printf(ptr, ...)"));
        assert!(rendered.contains("call i32 (ptr, ...) @printf(ptr @.ax_fmt_i32, i32 7)"));
        assert!(rendered.contains("select i1 1, ptr @.ax_text_true, ptr @.ax_text_false"));
    }

    #[test]
    fn renders_string_literal_println_calls() {
        let rendered = render(
            "\
fn main() -> i32 {
    println(\"hello\");
    println(\"C:\\\\AX\");
    return 0;
}
",
        );

        assert!(
            rendered.contains("@.ax_str_0 = private unnamed_addr constant [6 x i8] c\"hello\\00\"")
        );
        assert!(
            rendered
                .contains("@.ax_str_1 = private unnamed_addr constant [6 x i8] c\"C:\\5CAX\\00\"")
        );
        assert!(rendered.contains("call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr @.ax_str_0)"));
    }

    #[test]
    fn renders_string_locals_params_and_return_values() {
        let rendered = render(
            "\
fn choose(left: string, right: string) -> string {
    return right;
}

fn main() -> i32 {
    let text: string = choose(\"ignored\", \"kept\");
    println(text);
    return 0;
}
",
        );

        assert!(rendered.contains("define ptr @ax_choose(ptr %arg0, ptr %arg1)"));
        assert!(rendered.contains("store ptr %arg0, ptr %local"));
        assert!(rendered.contains("ret ptr %t"));
        assert!(rendered.contains("= call ptr @ax_choose(ptr @.ax_str_0, ptr @.ax_str_1)"));
        assert!(rendered.contains("call i32 (ptr, ...) @printf(ptr @.ax_fmt_str, ptr %t"));
    }

    #[test]
    fn renders_string_len_and_content_comparisons() {
        let rendered = render(
            "\
fn same(left: string, right: string) -> bool {
    return left == right;
}

fn main() -> i32 {
    let text: string = \"AX\";
    if (same(text, \"AX\") && text != \"BY\") {
        return string_len(text) + len(\"tool\");
    }
    return 1;
}
",
        );

        assert!(rendered.contains("declare i32 @strcmp(ptr, ptr)"));
        assert!(rendered.contains("define private i32 @ax_string_len(ptr %text)"));
        assert!(rendered.contains("call i32 @strcmp(ptr"));
        assert!(rendered.contains("icmp eq i32"));
        assert!(rendered.contains("icmp ne i32"));
        assert!(rendered.contains("call i32 @ax_string_len(ptr"));
    }

    #[test]
    fn renders_string_concat_and_to_string_values() {
        let rendered = render(
            "\
fn describe(value: i32, enabled: bool, label: string) -> string {
    return label + \"=\" + to_string(value) + \", enabled=\" + to_string(enabled);
}

fn main() -> i32 {
    let message: string = describe(7, true, \"count\") + \" done\";
    println(message);
    return string_len(message);
}
",
        );

        assert!(rendered.contains("declare ptr @malloc(i64)"));
        assert!(rendered.contains("declare ptr @memcpy(ptr, ptr, i64)"));
        assert!(rendered.contains("declare i32 @snprintf(ptr, i64, ptr, ...)"));
        assert!(rendered.contains("define private ptr @ax_string_concat(ptr %left, ptr %right)"));
        assert!(rendered.contains("define private ptr @ax_i32_to_string(i32 %value)"));
        assert!(rendered.contains("call ptr @ax_string_concat(ptr"));
        assert!(rendered.contains("call ptr @ax_i32_to_string(i32"));
        assert!(rendered.contains("select i1"));
    }

    #[test]
    fn renders_fixed_array_literals_index_reads_and_len() {
        let rendered = render(
            "\
fn pick(values: [i32; 4], index: i32) -> i32 {
    return values[index];
}

fn main() -> i32 {
    let values: [i32; 4] = [3, 5, 8, 13];
    return values[0] + pick(values, len(values) - 1);
}
",
        );

        assert!(rendered.contains("define i32 @ax_pick([4 x i32] %arg0, i32 %arg1)"));
        assert!(rendered.contains("store [4 x i32] [i32 3, i32 5, i32 8, i32 13]"));
        assert!(rendered.contains("getelementptr [4 x i32], ptr %local"));
        assert!(rendered.contains("icmp slt i32"));
        assert!(rendered.contains("icmp sge i32"));
        assert!(rendered.contains("call i32 @ax_pick([4 x i32]"));
    }
}
