pub mod ai;
pub mod ast;
pub mod build;
pub mod cli;
pub mod context;
pub mod diagnostics;
pub mod formatter;
pub mod frontend;
pub mod hir;
pub mod interpreter;
pub mod lexer;
pub mod mir;
pub mod parser;
pub mod project;
pub mod semantic;
pub mod source;
pub mod token;

pub use cli::run_cli;
