use serde::Serialize;

use crate::source::Span;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum TokenKind {
    FnKw,
    StructKw,
    EnumKw,
    TraitKw,
    ImplKw,
    ConstKw,
    PubKw,
    ModuleKw,
    ImportKw,
    MatchKw,
    LetKw,
    MutKw,
    ReturnKw,
    BreakKw,
    ContinueKw,
    IfKw,
    ElseKw,
    WhileKw,
    ForKw,
    InKw,
    TrueKw,
    FalseKw,
    Identifier,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Dot,
    Colon,
    Semicolon,
    Arrow,
    FatArrow,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    AmpAmp,
    PipePipe,
    Bang,
    Equal,
    EqualEqual,
    BangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Eof,
}

impl TokenKind {
    pub fn display(self) -> &'static str {
        match self {
            Self::FnKw => "`fn`",
            Self::StructKw => "`struct`",
            Self::EnumKw => "`enum`",
            Self::TraitKw => "`trait`",
            Self::ImplKw => "`impl`",
            Self::ConstKw => "`const`",
            Self::PubKw => "`pub`",
            Self::ModuleKw => "`module`",
            Self::ImportKw => "`import`",
            Self::MatchKw => "`match`",
            Self::LetKw => "`let`",
            Self::MutKw => "`mut`",
            Self::ReturnKw => "`return`",
            Self::BreakKw => "`break`",
            Self::ContinueKw => "`continue`",
            Self::IfKw => "`if`",
            Self::ElseKw => "`else`",
            Self::WhileKw => "`while`",
            Self::ForKw => "`for`",
            Self::InKw => "`in`",
            Self::TrueKw => "`true`",
            Self::FalseKw => "`false`",
            Self::Identifier => "identifier",
            Self::IntLiteral => "integer literal",
            Self::FloatLiteral => "float literal",
            Self::StringLiteral => "string literal",
            Self::LParen => "`(`",
            Self::RParen => "`)`",
            Self::LBracket => "`[`",
            Self::RBracket => "`]`",
            Self::LBrace => "`{`",
            Self::RBrace => "`}`",
            Self::Comma => "`,`",
            Self::Dot => "`.`",
            Self::Colon => "`:`",
            Self::Semicolon => "`;`",
            Self::Arrow => "`->`",
            Self::FatArrow => "`=>`",
            Self::Plus => "`+`",
            Self::Minus => "`-`",
            Self::Star => "`*`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::AmpAmp => "`&&`",
            Self::PipePipe => "`||`",
            Self::Bang => "`!`",
            Self::Equal => "`=`",
            Self::EqualEqual => "`==`",
            Self::BangEqual => "`!=`",
            Self::Less => "`<`",
            Self::LessEqual => "`<=`",
            Self::Greater => "`>`",
            Self::GreaterEqual => "`>=`",
            Self::Eof => "end of file",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    pub lexeme: String,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span, lexeme: impl Into<String>) -> Self {
        Self {
            kind,
            span,
            lexeme: lexeme.into(),
        }
    }
}
